-- AURA - Feature: Usuarios corporativos (2026-07-14).
--
-- Las empresas contratan Aura como beneficio para sus empleados. Un empleado
-- se registra normal en Aura; si el dominio de su mail coincide con una empresa
-- activa, se lo vincula automáticamente y recibe créditos. Cada mes se le
-- vuelven a acreditar los créditos del beneficio.
--
-- Este archivo es IDEMPOTENTE: se puede correr varias veces sin duplicar nada.
--
-- ORDEN DE APLICACIÓN:
--   PARTES A–E: correr siempre (crea tablas, columnas, trigger y RPCs).
--   PARTE F (pg_cron): correr DESPUÉS de deployar la Edge Function
--     `acreditar-creditos-corporativos` y de setear el CRON_SECRET.
--     Reemplazar <PROJECT_REF>, <ANON_KEY> y <CRON_SECRET>.


-- ══════════════════════════════════════════════════════════════════════════
-- PARTE A — Tabla empresas + columnas nuevas en usuarios
-- ══════════════════════════════════════════════════════════════════════════

create table if not exists public.empresas (
  id                    bigint generated by default as identity primary key,
  nombre                text    not null,
  dominio_mail          text    not null,
  creditos_por_empleado integer not null default 0,
  activa                boolean not null default true,
  created_at            timestamptz not null default now()
);

-- El dominio debe ser único e insensible a mayúsculas: dos empresas no pueden
-- reclamar el mismo dominio. Normalizamos siempre a minúsculas al escribir.
create unique index if not exists empresas_dominio_mail_key
  on public.empresas (lower(dominio_mail));

alter table public.usuarios
  add column if not exists empresa_id     bigint references public.empresas(id) on delete set null,
  add column if not exists es_corporativo boolean not null default false;

create index if not exists usuarios_empresa_id_idx
  on public.usuarios (empresa_id);

-- RLS de empresas: el backoffice usa RPCs security definer (que bypassan RLS),
-- así que desde el cliente solo hace falta que un usuario pueda leer los datos
-- de SU propia empresa para el badge "Beneficio [Empresa]". Nada más.
alter table public.empresas enable row level security;

grant select on public.empresas to authenticated;

drop policy if exists empresas_select_propia on public.empresas;
create policy empresas_select_propia on public.empresas
  for select to authenticated
  using (
    id = (select u.empresa_id from public.usuarios u where u.id = auth.uid())
  );


-- ══════════════════════════════════════════════════════════════════════════
-- PARTE B — Vinculación + acreditación de UN usuario a UNA empresa
-- ══════════════════════════════════════════════════════════════════════════
--
-- Helper reutilizado por el trigger de registro y por el backfill. Idempotente:
-- solo actúa si el usuario todavía NO está vinculado a ninguna empresa
-- (empresa_id null), así nunca re-acredita el crédito inicial.

create or replace function public.vincular_usuario_a_empresa(
  p_user_id uuid,
  p_email   text
) returns void
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_dominio text;
  v_empresa record;
  v_ya_vinculado boolean;
begin
  if p_user_id is null or p_email is null or position('@' in p_email) = 0 then
    return;
  end if;

  -- Si ya tiene empresa asignada, no tocamos nada (evita doble crédito).
  select (empresa_id is not null) into v_ya_vinculado
    from public.usuarios where id = p_user_id;
  if coalesce(v_ya_vinculado, true) then
    return;
  end if;

  v_dominio := lower(split_part(p_email, '@', 2));

  select id, nombre, creditos_por_empleado
    into v_empresa
    from public.empresas
   where lower(dominio_mail) = v_dominio
     and activa = true
   limit 1;

  if not found then
    return;
  end if;

  update public.usuarios
     set empresa_id = v_empresa.id,
         es_corporativo = true
   where id = p_user_id;

  -- Créditos iniciales del beneficio (vencen en 30 días, igual que un plan).
  -- La fuente 'corporativo' es la que la app usa para mostrar el badge.
  if coalesce(v_empresa.creditos_por_empleado, 0) > 0 then
    perform public.grant_user_credits(
      p_user_id,
      v_empresa.creditos_por_empleado,
      'corporativo',
      to_char((now() + interval '30 days')::date, 'YYYY-MM-DD'),
      'Beneficio ' || v_empresa.nombre
    );
  end if;
end;
$$;


-- ══════════════════════════════════════════════════════════════════════════
-- PARTE C — Trigger: detección automática al registrarse (PARTE 2 del spec)
-- ══════════════════════════════════════════════════════════════════════════
--
-- Se dispara en el INSERT de usuarios, así cubre TODAS las vías de registro
-- (email, Google, Apple, o el insert de ensureUsuarioCreado en Flutter) sin
-- depender del cliente. Solo lee NEW.email y delega en el helper.

create or replace function public.trg_vincular_usuario_empresa()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $$
begin
  perform public.vincular_usuario_a_empresa(new.id, new.email);
  return new;
end;
$$;

drop trigger if exists trg_vincular_usuario_empresa on public.usuarios;
create trigger trg_vincular_usuario_empresa
  after insert on public.usuarios
  for each row execute function public.trg_vincular_usuario_empresa();


-- ══════════════════════════════════════════════════════════════════════════
-- PARTE D — Acreditación mensual (PARTE 3 del spec)
-- ══════════════════════════════════════════════════════════════════════════
--
-- La Edge Function `acreditar-creditos-corporativos` (cron día 1, 00:00 ART)
-- llama a esta RPC con el service role. Recorre las empresas activas y acredita
-- los créditos del mes a cada empleado corporativo, con fuente 'corporativo'.

create or replace function public.acreditar_creditos_corporativos()
returns json
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_empresa   record;
  v_user      record;
  v_empresas  int := 0;
  v_usuarios  int := 0;
  v_creditos  int := 0;
  -- Vencimiento a 30 días desde hoy (hora Argentina).
  v_expiry text := to_char(
    ((now() at time zone 'America/Argentina/Buenos_Aires')::date + 30),
    'YYYY-MM-DD'
  );
begin
  for v_empresa in
    select id, nombre, creditos_por_empleado
      from public.empresas
     where activa = true
       and coalesce(creditos_por_empleado, 0) > 0
  loop
    v_empresas := v_empresas + 1;
    for v_user in
      select id
        from public.usuarios
       where empresa_id = v_empresa.id
         and es_corporativo = true
    loop
      perform public.grant_user_credits(
        v_user.id,
        v_empresa.creditos_por_empleado,
        'corporativo',
        v_expiry,
        'Beneficio ' || v_empresa.nombre
      );
      v_usuarios := v_usuarios + 1;
      v_creditos := v_creditos + v_empresa.creditos_por_empleado;
    end loop;
  end loop;

  return json_build_object(
    'empresas', v_empresas,
    'usuarios', v_usuarios,
    'creditos', v_creditos
  );
end;
$$;

grant execute on function public.acreditar_creditos_corporativos() to service_role;


-- ══════════════════════════════════════════════════════════════════════════
-- PARTE E — RPCs del backoffice (PARTE 4 del spec)
-- ══════════════════════════════════════════════════════════════════════════
--
-- Todas verifican is_admin() (superadmin de Aura). Se invocan desde el panel
-- admin con el JWT del usuario, por eso el grant a authenticated.

-- Inicio del mes actual (hora Argentina), como instante timestamptz, para
-- medir "créditos usados este mes" sobre reservas.created_at.
create or replace function public.aura_inicio_mes_art()
returns timestamptz
language sql
stable
as $$
  select (date_trunc('month', (now() at time zone 'America/Argentina/Buenos_Aires')))
         at time zone 'America/Argentina/Buenos_Aires';
$$;

-- E.1 — Listar empresas con nº de empleados y créditos usados este mes.
create or replace function public.admin_list_empresas()
returns table (
  id                    bigint,
  nombre                text,
  dominio_mail          text,
  creditos_por_empleado integer,
  activa                boolean,
  created_at            timestamptz,
  empleados_count       bigint,
  creditos_usados_mes   bigint
)
language plpgsql
security definer
set search_path to 'public'
as $$
begin
  if not public.is_admin() then
    raise exception 'No autorizado';
  end if;

  return query
  select
    e.id,
    e.nombre,
    e.dominio_mail,
    e.creditos_por_empleado,
    e.activa,
    e.created_at,
    coalesce(emp.cnt, 0)      as empleados_count,
    coalesce(uso.creditos, 0) as creditos_usados_mes
  from public.empresas e
  left join lateral (
    select count(*)::bigint as cnt
      from public.usuarios u
     where u.empresa_id = e.id
  ) emp on true
  left join lateral (
    select coalesce(sum(r.creditos_usados), 0)::bigint as creditos
      from public.reservas r
      join public.usuarios u on u.id = r.usuario_id
     where u.empresa_id = e.id
       and r.estado <> 'cancelada'
       and r.created_at >= public.aura_inicio_mes_art()
  ) uso on true
  order by e.activa desc, lower(e.nombre);
end;
$$;

-- E.2 — Crear / editar empresa. Al crear (o si estaba inactiva y se activa),
-- hace backfill: vincula + acredita a los usuarios ya registrados cuyo mail
-- coincide con el dominio y que todavía no tienen empresa.
create or replace function public.admin_upsert_empresa(
  p_id                    bigint  default null,
  p_nombre                text    default null,
  p_dominio_mail          text    default null,
  p_creditos_por_empleado integer default 0,
  p_activa                boolean default true
) returns bigint
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_id       bigint;
  v_dominio  text := lower(trim(coalesce(p_dominio_mail, '')));
  v_nombre   text := trim(coalesce(p_nombre, ''));
  v_user     record;
begin
  if not public.is_admin() then
    raise exception 'No autorizado';
  end if;
  if v_nombre = '' then
    raise exception 'El nombre es obligatorio';
  end if;
  if v_dominio = '' or position('@' in v_dominio) > 0 or position('.' in v_dominio) = 0 then
    raise exception 'Dominio inválido. Ingresá solo el dominio, ej: empresa.com';
  end if;

  if p_id is null then
    insert into public.empresas (nombre, dominio_mail, creditos_por_empleado, activa)
    values (v_nombre, v_dominio, greatest(coalesce(p_creditos_por_empleado, 0), 0),
            coalesce(p_activa, true))
    returning id into v_id;

    perform public.log_admin_action('Crear empresa', v_nombre, 'empresas');
  else
    v_id := p_id;
    update public.empresas
       set nombre                = v_nombre,
           dominio_mail          = v_dominio,
           creditos_por_empleado = greatest(coalesce(p_creditos_por_empleado, 0), 0),
           activa                = coalesce(p_activa, activa)
     where id = v_id;

    perform public.log_admin_action('Editar empresa', v_nombre, 'empresas');
  end if;

  -- Backfill: si la empresa quedó activa, enganchamos a los empleados que ya
  -- estaban registrados antes de darla de alta. Idempotente (solo toca a los
  -- que aún no tienen empresa_id, así no re-acredita).
  if coalesce(p_activa, true) then
    for v_user in
      select id, email
        from public.usuarios
       where empresa_id is null
         and email is not null
         and lower(split_part(email, '@', 2)) = v_dominio
    loop
      perform public.vincular_usuario_a_empresa(v_user.id, v_user.email);
    end loop;
  end if;

  return v_id;
end;
$$;

-- E.3 — Activar / desactivar empresa.
create or replace function public.admin_set_empresa_activa(
  p_id     bigint,
  p_activa boolean
) returns void
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_nombre text;
begin
  if not public.is_admin() then
    raise exception 'No autorizado';
  end if;

  update public.empresas set activa = coalesce(p_activa, false)
   where id = p_id
   returning nombre into v_nombre;

  perform public.log_admin_action(
    case when p_activa then 'Activar empresa' else 'Desactivar empresa' end,
    coalesce(v_nombre, p_id::text),
    'empresas'
  );
end;
$$;

-- E.4 — Empleados registrados de una empresa: saldo actual y créditos usados
-- este mes por cada uno.
create or replace function public.admin_list_empresa_empleados(
  p_empresa_id bigint
)
returns table (
  id                  uuid,
  nombre              text,
  email               text,
  creditos            integer,
  creditos_usados_mes bigint
)
language plpgsql
security definer
set search_path to 'public'
as $$
begin
  if not public.is_admin() then
    raise exception 'No autorizado';
  end if;

  return query
  select
    u.id,
    u.nombre,
    u.email,
    coalesce(u.creditos, 0) as creditos,
    coalesce(uso.creditos, 0)::bigint as creditos_usados_mes
  from public.usuarios u
  left join lateral (
    select coalesce(sum(r.creditos_usados), 0) as creditos
      from public.reservas r
     where r.usuario_id = u.id
       and r.estado <> 'cancelada'
       and r.created_at >= public.aura_inicio_mes_art()
  ) uso on true
  where u.empresa_id = p_empresa_id
  order by lower(u.nombre);
end;
$$;

grant execute on function public.admin_list_empresas()                 to authenticated;
grant execute on function public.admin_upsert_empresa(bigint, text, text, integer, boolean) to authenticated;
grant execute on function public.admin_set_empresa_activa(bigint, boolean)            to authenticated;
grant execute on function public.admin_list_empresa_empleados(bigint)  to authenticated;
grant execute on function public.aura_inicio_mes_art()                 to authenticated, service_role;


-- ══════════════════════════════════════════════════════════════════════════
-- PARTE F — Scheduling con pg_cron (correr al final, con placeholders)
-- ══════════════════════════════════════════════════════════════════════════
--
-- Requisitos previos:
--   1. Deployá la Edge Function:
--        supabase functions deploy acreditar-creditos-corporativos --no-verify-jwt
--   2. Reutiliza el CRON_SECRET que ya usás para los otros crons (si no lo
--      seteaste todavía: supabase secrets set CRON_SECRET=algo-largo-y-secreto).
--   3. Reemplazá <PROJECT_REF>, <ANON_KEY> y <CRON_SECRET>.
--
-- pg_cron corre en UTC. Argentina es UTC-3 (sin DST): 00:00 ART = 03:00 UTC.
-- Día 1 de cada mes a las 00:00 ART  ->  '0 3 1 * *'.

create extension if not exists pg_cron;
create extension if not exists pg_net;

select cron.schedule(
  'acreditar-creditos-corporativos-mensual',
  '0 3 1 * *',
  $$
  select net.http_post(
    url     := 'https://<PROJECT_REF>.supabase.co/functions/v1/acreditar-creditos-corporativos',
    headers := jsonb_build_object(
      'Content-Type',   'application/json',
      'Authorization',  'Bearer <ANON_KEY>',
      'x-cron-secret',  '<CRON_SECRET>'
    ),
    body    := '{}'::jsonb
  );
  $$
);

-- Verificación:
--   select jobname, schedule, active from cron.job order by jobname;
--
-- Prueba manual del acreditado (sin esperar al día 1):
--   select public.acreditar_creditos_corporativos();
