-- ============================================================================
-- TANDA B — Categorias: fuente unica, CRUD completo, multiples por clase
-- ============================================================================
-- Idempotente. Correr entero.
-- ============================================================================

begin;

-- ══════════════════════════════════════════════════════════════════════════
-- FIX 2 — Catalogo de categorias con CRUD real
-- ══════════════════════════════════════════════════════════════════════════
-- La tabla se creo desde el dashboard y nunca estuvo versionada, igual que
-- los RPC que la manejan (add/rename/delete solo existian compilados en el
-- bundle web). Se define todo aca.

create table if not exists public.study_categories (
  id     bigint generated by default as identity primary key,
  nombre text not null,
  activa boolean not null default true,
  created_at timestamptz not null default now()
);

-- Por si la tabla ya existia sin estas columnas.
alter table public.study_categories
  add column if not exists activa boolean not null default true;

create unique index if not exists study_categories_nombre_uniq
  on public.study_categories (lower(trim(nombre)));

comment on column public.study_categories.activa is
  'Categoria disponible para asignar. Desactivar la saca de los selectores sin borrar el historial de las clases que ya la usan.';

alter table public.study_categories enable row level security;

-- Lectura publica: la app la necesita para los filtros del usuario.
drop policy if exists "study_categories select" on public.study_categories;
create policy "study_categories select"
  on public.study_categories for select
  using (true);

-- Escritura: solo por los RPC (security definer). Sin policies de escritura,
-- ni anon ni authenticated pueden tocarla directo.


-- ── RPC: listar ────────────────────────────────────────────────────────────
drop function if exists public.admin_list_studio_categories();

create or replace function public.admin_list_studio_categories()
returns table(id bigint, nombre text, activa boolean, en_uso bigint)
language sql
stable
security definer
set search_path = public
as $$
  select
    sc.id,
    sc.nombre,
    sc.activa,
    -- Cuantos estudios la tienen asignada: sirve para avisar antes de borrar.
    (select count(*)
       from public.estudios e
      where sc.nombre = any(e.categorias)) as en_uso
  from public.study_categories sc
  order by sc.activa desc, sc.nombre;
$$;

grant execute on function public.admin_list_studio_categories() to authenticated;


-- ── RPC: crear ─────────────────────────────────────────────────────────────
drop function if exists public.admin_add_studio_category(text);

create or replace function public.admin_add_studio_category(p_nombre text)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  v_nombre text := trim(coalesce(p_nombre, ''));
begin
  if not public.is_admin() then
    raise exception 'No autorizado';
  end if;

  if v_nombre = '' then
    return json_build_object('ok', false, 'error', 'El nombre no puede estar vacio');
  end if;

  if exists (
    select 1 from public.study_categories
     where lower(trim(nombre)) = lower(v_nombre)
  ) then
    return json_build_object('ok', false, 'error', 'Ya existe una categoria con ese nombre');
  end if;

  insert into public.study_categories (nombre, activa)
  values (v_nombre, true);

  return json_build_object('ok', true, 'nombre', v_nombre);
end;
$$;

grant execute on function public.admin_add_studio_category(text) to authenticated;


-- ── RPC: renombrar ─────────────────────────────────────────────────────────
-- Propaga el nombre nuevo a estudios.categorias, clases.categorias y
-- horarios_fijos.categorias, si no las asignaciones quedan colgadas.
-- La version vieja usaba p_old_name/p_new_name: se dropea por firma.
drop function if exists public.admin_rename_studio_category(text, text);

create or replace function public.admin_rename_studio_category(
  p_actual text,
  p_nuevo  text
)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actual text := trim(coalesce(p_actual, ''));
  v_nuevo  text := trim(coalesce(p_nuevo, ''));
begin
  if not public.is_admin() then
    raise exception 'No autorizado';
  end if;

  if v_actual = '' or v_nuevo = '' then
    return json_build_object('ok', false, 'error', 'Nombres invalidos');
  end if;

  if exists (
    select 1 from public.study_categories
     where lower(trim(nombre)) = lower(v_nuevo)
       and lower(trim(nombre)) <> lower(v_actual)
  ) then
    return json_build_object('ok', false, 'error', 'Ya existe una categoria con ese nombre');
  end if;

  update public.study_categories
     set nombre = v_nuevo
   where lower(trim(nombre)) = lower(v_actual);

  update public.estudios
     set categorias = array_replace(categorias, v_actual, v_nuevo)
   where v_actual = any(categorias);

  update public.clases
     set categorias = array_replace(categorias, v_actual, v_nuevo)
   where v_actual = any(categorias);

  update public.horarios_fijos
     set categorias = array_replace(categorias, v_actual, v_nuevo)
   where v_actual = any(categorias);

  return json_build_object('ok', true, 'nombre', v_nuevo);
end;
$$;

grant execute on function public.admin_rename_studio_category(text, text)
  to authenticated;


-- ── RPC: activar / desactivar ──────────────────────────────────────────────
-- Preferible a borrar: saca la categoria de los selectores pero no toca las
-- clases que ya la tienen asignada.
drop function if exists public.admin_toggle_studio_category(text, boolean);

create or replace function public.admin_toggle_studio_category(
  p_nombre text,
  p_activa boolean
)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  v_nombre text := trim(coalesce(p_nombre, ''));
begin
  if not public.is_admin() then
    raise exception 'No autorizado';
  end if;

  update public.study_categories
     set activa = coalesce(p_activa, true)
   where lower(trim(nombre)) = lower(v_nombre);

  if not found then
    return json_build_object('ok', false, 'error', 'Categoria no encontrada');
  end if;

  return json_build_object('ok', true, 'nombre', v_nombre, 'activa', p_activa);
end;
$$;

grant execute on function public.admin_toggle_studio_category(text, boolean)
  to authenticated;


-- ── RPC: eliminar ──────────────────────────────────────────────────────────
-- Borra la categoria y la saca de todas las asignaciones.
drop function if exists public.admin_delete_studio_category(text);

create or replace function public.admin_delete_studio_category(p_nombre text)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  v_nombre text := trim(coalesce(p_nombre, ''));
  v_afectados int := 0;
begin
  if not public.is_admin() then
    raise exception 'No autorizado';
  end if;

  delete from public.study_categories
   where lower(trim(nombre)) = lower(v_nombre);

  update public.estudios
     set categorias = array_remove(categorias, v_nombre)
   where v_nombre = any(categorias);
  get diagnostics v_afectados = row_count;

  update public.clases
     set categorias = array_remove(categorias, v_nombre)
   where v_nombre = any(categorias);

  update public.horarios_fijos
     set categorias = array_remove(categorias, v_nombre)
   where v_nombre = any(categorias);

  return json_build_object('ok', true, 'estudios_afectados', v_afectados);
end;
$$;

grant execute on function public.admin_delete_studio_category(text)
  to authenticated;


-- ══════════════════════════════════════════════════════════════════════════
-- FIX 3 — Multiples categorias por clase y por horario fijo (max 5)
-- ══════════════════════════════════════════════════════════════════════════
-- Mismo patron que estudios: columna nueva text[] como fuente de verdad y el
-- escalar `categoria` sincronizado por trigger, para no romper lo legacy.

alter table public.clases
  add column if not exists categorias text[] not null default '{}';

alter table public.horarios_fijos
  add column if not exists categorias text[] not null default '{}';

-- Backfill desde el escalar.
update public.clases
   set categorias = array[trim(categoria)]
 where categorias = '{}'
   and categoria is not null
   and trim(categoria) <> '';

update public.horarios_fijos
   set categorias = array[trim(categoria)]
 where categorias = '{}'
   and categoria is not null
   and trim(categoria) <> '';

-- Trigger compartido: valida el tope de 5 y sincroniza el escalar.
create or replace function public.sync_categorias_clase()
returns trigger
language plpgsql
as $$
begin
  -- Cliente viejo que solo mando el escalar: sembramos el array.
  if (new.categorias is null or new.categorias = '{}')
     and new.categoria is not null
     and trim(new.categoria) <> '' then
    new.categorias := array[trim(new.categoria)];
  end if;

  if new.categorias is not null
     and array_length(new.categorias, 1) > 5 then
    raise exception 'Maximo 5 categorias por clase (recibidas %)',
      array_length(new.categorias, 1);
  end if;

  new.categoria := case
    when new.categorias is null
      or array_length(new.categorias, 1) is null
    then null
    else new.categorias[1]
  end;

  return new;
end;
$$;

drop trigger if exists trg_sync_categorias_clase on public.clases;
create trigger trg_sync_categorias_clase
  before insert or update on public.clases
  for each row execute function public.sync_categorias_clase();

drop trigger if exists trg_sync_categorias_horario on public.horarios_fijos;
create trigger trg_sync_categorias_horario
  before insert or update on public.horarios_fijos
  for each row execute function public.sync_categorias_clase();

create index if not exists clases_categorias_gin
  on public.clases using gin (categorias);

create index if not exists horarios_fijos_categorias_gin
  on public.horarios_fijos using gin (categorias);


-- ══════════════════════════════════════════════════════════════════════════
-- DESACOPLAR PRECIO DE CATEGORIA
-- ══════════════════════════════════════════════════════════════════════════
-- El precio de una clase sale del valor propio del estudio (fijo o rango)
-- que define el admin, nunca de la categoria. `calcular_precio_clase` (v3)
-- ya ignoraba p_categoria; lo que quedaba era que generar_clases_estudio
-- buscara la categoria del estudio solo para pasarsela. Se saca ese lookup
-- y ademas se propagan las categorias del horario fijo a la clase.

-- drop previo: la version deployada tiene otro default (4 o 13) y puede
-- tener otro tipo de retorno; `create or replace` no puede cambiarlo.
drop function if exists public.generar_clases_estudio(int, int);

create or replace function public.generar_clases_estudio(
  p_estudio_id int,
  p_weeks int default 9
)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  v_now          timestamp := (
    now() at time zone 'America/Argentina/Buenos_Aires'
  );
  v_week_start   date;
  v_week_offset  int;
  v_h            record;
  v_creadas      int := 0;
  v_omitidas     int := 0;
  v_fecha        timestamp;
  v_hora         int;
  v_minuto       int;
  v_hora_text    text;
  v_existente_id int;
  v_resultado    json;
  v_creditos     int;
  v_tipo         text;
begin
  v_week_start := v_now::date - ((extract(isodow from v_now)::int) - 1);

  for v_h in
    select * from public.horarios_fijos
     where estudio_id = p_estudio_id
       and coalesce(activo, true) = true
  loop
    if v_h.dia_semana is null
       or v_h.dia_semana < 1
       or v_h.dia_semana > 7 then
      v_omitidas := v_omitidas + 1;
      continue;
    end if;

    if v_h.nombre is null or trim(v_h.nombre) = '' then
      v_omitidas := v_omitidas + 1;
      continue;
    end if;

    v_hora   := coalesce(extract(hour from v_h.hora_inicio)::int, 8);
    v_minuto := coalesce(extract(minute from v_h.hora_inicio)::int, 0);
    v_hora_text := lpad(v_hora::text, 2, '0')
                   || ':'
                   || lpad(v_minuto::text, 2, '0');

    -- p_categoria = null: el precio NO depende de la categoria.
    v_resultado := public.calcular_precio_clase(
      p_estudio_id,
      null,
      v_h.dia_semana,
      v_hora_text
    );
    v_creditos := (v_resultado->>'creditos')::int;
    v_tipo := v_resultado->>'tipo';

    for v_week_offset in 0..(p_weeks - 1) loop
      v_fecha := (
        v_week_start + (v_week_offset * 7 + (v_h.dia_semana - 1))
      )::timestamp
      + make_interval(hours => v_hora, mins => v_minuto);

      select id into v_existente_id
        from public.clases
       where estudio_id = p_estudio_id
         and horario_fijo_id = v_h.id
         and fecha between v_fecha - interval '1 hour'
                       and v_fecha + interval '1 hour'
       limit 1;

      if v_existente_id is not null then
        v_omitidas := v_omitidas + 1;
        continue;
      end if;

      insert into public.clases (
        estudio_id, horario_fijo_id, nombre, instructor,
        instructor_descripcion, incluye, imagen_url, imagen_ajuste,
        galeria_urls, fecha, duracion_min, lugares_total,
        lugares_disponibles, creditos, reserva_cierre_minutos,
        cancelacion_cierre_minutos, categorias, sala, tipo_precio
      ) values (
        p_estudio_id, v_h.id, v_h.nombre, v_h.instructor,
        v_h.instructor_descripcion, v_h.incluye, v_h.imagen_url,
        v_h.imagen_ajuste, v_h.galeria_urls, v_fecha,
        coalesce(v_h.duracion_min, 60),
        coalesce(v_h.lugares_total, 12),
        coalesce(v_h.lugares_total, 12),
        v_creditos,
        v_h.reserva_cierre_minutos,
        v_h.cancelacion_cierre_minutos,
        coalesce(v_h.categorias, '{}'),
        v_h.sala, v_tipo
      );
      v_creadas := v_creadas + 1;
    end loop;
  end loop;

  return json_build_object('creadas', v_creadas, 'omitidas', v_omitidas);
end;
$$;

grant execute on function public.generar_clases_estudio(int, int)
  to authenticated, service_role;


-- `creditos_por_categoria` queda obsoleta: el precio no se deriva de la
-- categoria. La dejamos en configuracion_global por si hay que auditarla,
-- pero el codigo Dart que la leia se elimina en esta misma tanda.
drop function if exists public.admin_set_creditos_por_categoria(text);

commit;

-- ── VERIFICACION (correr aparte) ───────────────────────────────────────────
-- select nombre, activa from public.study_categories order by activa desc, nombre;
--
-- select count(*) filter (where categorias = '{}') as sin_categoria,
--        count(*) filter (where array_length(categorias,1) > 1) as multi,
--        count(*) as total
--   from public.clases;
--
-- select proname from pg_proc
--  where proname like 'admin_%studio_categor%' order by proname;
