$file = "C:\Users\sofir\OneDrive\Escritorio\Sofi\aura_flutter\lib\screens\clases\detalle_clase_screen.dart"
$lines = [System.Collections.Generic.List[string]](Get-Content $file)

$start = 426
$count = 40
$replacement = [System.Collections.Generic.List[string]]@(
'                        child: Row(',
'                          crossAxisAlignment: CrossAxisAlignment.start,',
'                          children: [',
'                            Expanded(',
'                              child: Column(',
'                                crossAxisAlignment: CrossAxisAlignment.start,',
'                                children: [',
'                                  RichText(',
'                                    text: TextSpan(',
'                                      children: [',
'                                        TextSpan(',
'                                          text: ''$creditos'',',
'                                          style: const TextStyle(',
'                                            color: AppColors.primary,',
'                                            fontSize: 24,',
'                                            fontWeight: FontWeight.w700,',
'                                          ),',
'                                        ),',
'                                        const TextSpan(',
'                                          text: '' créditos'',',
'                                          style: TextStyle(',
'                                            color: AppColors.primary,',
'                                            fontSize: 14,',
'                                            fontWeight: FontWeight.w700,',
'                                          ),',
'                                        ),',
'                                      ],',
'                                    ),',
'                                  ),',
'                                  const SizedBox(height: 6),',
'                                  const Text(',
'                                    ''Precio de esta clase'',',
'                                    style: TextStyle(',
'                                      color: Color(0xFFA7A09A),',
'                                      fontSize: 14,',
'                                    ),',
'                                  ),',
'                                ],',
'                              ),',
'                            ),',
'                            const SizedBox(width: 22),',
'                            Expanded(',
'                              child: Column(',
'                                crossAxisAlignment: CrossAxisAlignment.start,',
'                                children: [',
'                                  const Text(',
'                                    ''Tu saldo'',',
'                                    style: TextStyle(',
'                                      color: Color(0xFFA7A09A),',
'                                      fontSize: 14,',
'                                    ),',
'                                  ),',
'                                  const SizedBox(height: 6),',
'                                  Text(',
'                                    ''$creditosSaldo créditos'',',
'                                    style: const TextStyle(',
'                                      color: AppColors.white,',
'                                      fontSize: 18,',
'                                      fontWeight: FontWeight.w700,',
'                                    ),',
'                                  ),',
'                                  const SizedBox(height: 6),',
'                                  Text(',
'                                    ''Quedan ${creditosSaldo - creditos} tras reservar'',',
'                                    style: const TextStyle(',
'                                      color: Color(0xFFA7A09A),',
'                                      fontSize: 14,',
'                                    ),',
'                                  ),',
'                                ],',
'                              ),',
'                            ),',
'                          ],',
'                        ),'
)

$lines.RemoveRange($start, $count)
$lines.InsertRange($start, $replacement)
Set-Content -LiteralPath $file -Value $lines -Encoding UTF8
