-- ============================================================================
-- TANDA C — Avisos: topes, dedup, confirmacion y envio multi-clase
-- ============================================================================
--
-- Hoy `AvisoAlumnosService.enviarAviso` hace todo desde el cliente: inserta
-- el log, lee las reservas e inserta las notificaciones. Eso no permite
-- imponer ningun tope (el cliente puede saltearselo) ni deduplicar bien.
--
-- Se mueve la logica a un RPC transaccional que ademas:
--   - valida que quien llama sea admin del estudio (no una profe)
--   - aplica el tope mensual de avisos GENERALES (configurable)
--   - deduplica: una persona en 3 clases del mismo envio recibe UNA sola
--   - registra a quien le corresponde canal externo (email/push) segun el
--     tope diario por usuario, cruzando todos los estudios
--   - manda copia de confirmacion a los admins del estudio y a las profes
--
-- SOBRE EL PUSH: no hay FCM/APNs todavia. La infraestructura de conteo y
-- dedup queda armada y el unico canal externo real hoy es el email de los
-- urgentes. Cuando se conecte FCM, `avisos_entregas.canal = 'push'` ya tiene
-- la informacion de a quien corresponde mandarle.
-- ============================================================================

-- ── Config: tope mensual de avisos generales ───────────────────────────────
insert into public.configuracion_global (clave, valor)
values ('avisos_generales_max_mes', '3')
on conflict (clave) do nothing;

-- ── Tabla: un registro por ENVIO ───────────────────────────────────────────
create table if not exists public.avisos_envios (
  id          bigint generated by default as identity primary key,
  estudio_id  int not null references public.estudios(id) on delete cascade,
  enviado_por uuid references public.usuarios(id) on delete set null,
  tipo        text not null check (tipo in ('aviso_general', 'urgente')),
  mensaje     text not null,
  clase_ids   bigint[] not null default '{}',
  destinatarios int not null default 0,
  created_at  timestamptz not null default now()
);

create index if not exists avisos_envios_estudio_fecha
  on public.avisos_envios (estudio_id, created_at desc);

-- ── Tabla: una fila por (envio, usuario, canal) ────────────────────────────
-- Es lo que permite deduplicar y contar el tope diario por usuario.
create table if not exists public.avisos_entregas (
  id         bigint generated by default as identity primary key,
  aviso_id   bigint not null references public.avisos_envios(id) on delete cascade,
  usuario_id uuid not null references public.usuarios(id) on delete cascade,
  canal      text not null check (canal in ('in_app', 'email', 'push')),
  created_at timestamptz not null default now()
);

create unique index if not exists avisos_entregas_uniq
  on public.avisos_entregas (aviso_id, usuario_id, canal);

create index if not exists avisos_entregas_usuario_fecha
  on public.avisos_entregas (usuario_id, canal, created_at desc);

alter table public.avisos_envios enable row level security;
alter table public.avisos_entregas enable row level security;

-- Solo el admin del estudio lee sus envios. La escritura va por el RPC.
drop policy if exists "estudio lee sus avisos" on public.avisos_envios;
create policy "estudio lee sus avisos"
  on public.avisos_envios for select
  to authenticated
  using (
    exists (
      select 1 from public.estudio_admins ea
       where ea.estudio_id = avisos_envios.estudio_id
         and ea.usuario_id = auth.uid()
    )
  );


-- ── Helper: cuantos generales le quedan al estudio este mes ────────────────
create or replace function public.avisos_generales_restantes(p_estudio_id int)
returns json
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_max   int;
  v_usados int;
  v_inicio timestamptz := date_trunc(
    'month',
    (now() at time zone 'America/Argentina/Buenos_Aires')
  ) at time zone 'America/Argentina/Buenos_Aires';
begin
  select coalesce(nullif(valor, '')::int, 3)
    into v_max
    from public.configuracion_global
   where clave = 'avisos_generales_max_mes';

  v_max := coalesce(v_max, 3);

  select count(*)
    into v_usados
    from public.avisos_envios
   where estudio_id = p_estudio_id
     and tipo = 'aviso_general'
     and created_at >= v_inicio;

  return json_build_object(
    'max', v_max,
    'usados', v_usados,
    'restantes', greatest(v_max - v_usados, 0),
    -- Primer dia del mes siguiente, para el mensaje de bloqueo.
    'reinicia', to_char(
      (date_trunc('month', (now() at time zone 'America/Argentina/Buenos_Aires'))
        + interval '1 month')::date,
      'DD/MM/YYYY'
    )
  );
end;
$$;

grant execute on function public.avisos_generales_restantes(int)
  to authenticated;


-- ── RPC principal: enviar aviso ────────────────────────────────────────────
create or replace function public.enviar_aviso_estudio(
  p_clase_ids bigint[],
  p_mensaje   text,
  p_tipo      text
)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid        uuid := auth.uid();
  v_estudio_id int;
  v_mensaje    text := trim(coalesce(p_mensaje, ''));
  v_tipo       text := coalesce(nullif(trim(p_tipo), ''), 'aviso_general');
  v_urgente    boolean;
  v_cupo       json;
  v_aviso_id   bigint;
  v_titulo     text;
  v_estudio_nombre text;
  v_destinatarios int := 0;
  v_push_max   int := 3;
  v_hoy        date := (now() at time zone 'America/Argentina/Buenos_Aires')::date;
begin
  if v_uid is null then
    return json_build_object('ok', false, 'error', 'No autenticado');
  end if;

  if v_mensaje = '' then
    return json_build_object('ok', false, 'error', 'El mensaje no puede estar vacio');
  end if;

  if v_tipo not in ('aviso_general', 'urgente') then
    return json_build_object('ok', false, 'error', 'Tipo invalido');
  end if;

  v_urgente := (v_tipo = 'urgente');

  if p_clase_ids is null or array_length(p_clase_ids, 1) is null then
    return json_build_object('ok', false, 'error', 'Elegi al menos una clase');
  end if;

  -- Tope de clases por envio: evita que un error mande a todo el padron.
  if array_length(p_clase_ids, 1) > 10 then
    return json_build_object(
      'ok', false,
      'error', 'Maximo 10 clases por envio'
    );
  end if;

  -- Todas las clases tienen que ser del mismo estudio, y quien manda tiene
  -- que ser ADMIN de ese estudio (una profe no manda avisos).
  select distinct c.estudio_id
    into v_estudio_id
    from public.clases c
   where c.id = any(p_clase_ids);

  if v_estudio_id is null then
    return json_build_object('ok', false, 'error', 'Clases no encontradas');
  end if;

  if (select count(distinct c.estudio_id)
        from public.clases c
       where c.id = any(p_clase_ids)) > 1 then
    return json_build_object(
      'ok', false,
      'error', 'Las clases tienen que ser del mismo estudio'
    );
  end if;

  if not exists (
    select 1 from public.estudio_admins ea
     where ea.estudio_id = v_estudio_id
       and ea.usuario_id = v_uid
       and ea.rol in ('estudio', 'admin_estudio')
  ) then
    return json_build_object('ok', false, 'error', 'Sin permisos');
  end if;

  -- Tope mensual: solo aplica a generales. Los urgentes son ilimitados
  -- porque son operativos (cancelaciones, cambios de horario).
  if not v_urgente then
    v_cupo := public.avisos_generales_restantes(v_estudio_id);
    if (v_cupo->>'restantes')::int <= 0 then
      return json_build_object(
        'ok', false,
        'error', 'limite_mensual',
        'cupo', v_cupo
      );
    end if;
  end if;

  select nombre into v_estudio_nombre
    from public.estudios where id = v_estudio_id;

  v_titulo := case
    when v_urgente then '🚨 ' || coalesce(v_estudio_nombre, 'Tu estudio')
                        || ' — Aviso urgente'
    else '📢 ' || coalesce(v_estudio_nombre, 'Tu estudio')
  end;

  insert into public.avisos_envios (
    estudio_id, enviado_por, tipo, mensaje, clase_ids
  ) values (
    v_estudio_id, v_uid, v_tipo, v_mensaje, p_clase_ids
  )
  returning id into v_aviso_id;

  -- ── Destinatarios: reservas CONFIRMADAS de esas clases, deduplicadas ────
  -- `distinct` resuelve el caso de la alumna anotada en varias clases del
  -- mismo envio: recibe un solo aviso.
  with destinatarios as (
    select distinct r.usuario_id
      from public.reservas r
     where r.clase_id = any(p_clase_ids)
       and r.estado = 'confirmada'
       and r.usuario_id is not null
  ),
  -- Cuantas notificaciones con canal externo ya recibio hoy, de CUALQUIER
  -- estudio. Los urgentes no cuentan para el tope.
  uso_hoy as (
    select ae.usuario_id, count(*) as enviadas
      from public.avisos_entregas ae
      join public.avisos_envios av on av.id = ae.aviso_id
     where ae.canal in ('push', 'email')
       and av.tipo <> 'urgente'
       and (ae.created_at at time zone 'America/Argentina/Buenos_Aires')::date
           = v_hoy
     group by ae.usuario_id
  ),
  ins_notif as (
    insert into public.notificaciones_usuario (
      usuario_id, titulo, mensaje, tipo, leida
    )
    select d.usuario_id, v_titulo, v_mensaje, 'aviso_estudio', false
      from destinatarios d
    returning usuario_id
  ),
  ins_in_app as (
    insert into public.avisos_entregas (aviso_id, usuario_id, canal)
    select v_aviso_id, d.usuario_id, 'in_app'
      from destinatarios d
    on conflict do nothing
    returning usuario_id
  ),
  ins_externo as (
    -- Canal externo (hoy email; manana tambien push):
    --   - urgente: siempre, sin tope
    --   - general: solo si el usuario no supero las 3 del dia
    insert into public.avisos_entregas (aviso_id, usuario_id, canal)
    select v_aviso_id,
           d.usuario_id,
           case when v_urgente then 'email' else 'push' end
      from destinatarios d
      left join uso_hoy u on u.usuario_id = d.usuario_id
     where v_urgente
        or coalesce(u.enviadas, 0) < v_push_max
    on conflict do nothing
    returning usuario_id
  )
  select count(*) into v_destinatarios from ins_notif;

  update public.avisos_envios
     set destinatarios = v_destinatarios
   where id = v_aviso_id;

  -- ── Copia de confirmacion al equipo del estudio ─────────────────────────
  -- Va a TODOS los admins y a las profes vinculadas, para que vean que el
  -- aviso salio. No se registra en avisos_entregas: no cuenta para topes.
  insert into public.notificaciones_usuario (
    usuario_id, titulo, mensaje, tipo, leida
  )
  select ea.usuario_id,
         '✅ Aviso enviado',
         'Se envio a ' || v_destinatarios || ' alumna'
           || case when v_destinatarios = 1 then '' else 's' end
           || ': "' || v_mensaje || '"',
         'aviso_confirmacion',
         false
    from public.estudio_admins ea
   where ea.estudio_id = v_estudio_id
     and ea.usuario_id <> v_uid;

  return json_build_object(
    'ok', true,
    'aviso_id', v_aviso_id,
    'destinatarios', v_destinatarios,
    'tipo', v_tipo,
    'cupo', case
      when v_urgente then null
      else public.avisos_generales_restantes(v_estudio_id)
    end
  );
end;
$$;

grant execute on function public.enviar_aviso_estudio(bigint[], text, text)
  to authenticated;


-- ── RPC: a quien hay que mandarle email de este aviso ───────────────────────
-- La usa la Edge Function aviso-alumnos-email. Devuelve solo los que tienen
-- canal 'email' registrado y no desactivaron las notificaciones.
create or replace function public.aviso_destinatarios_email(p_aviso_id bigint)
returns table(email text)
language sql
stable
security definer
set search_path = public
as $$
  select u.email
    from public.avisos_entregas ae
    join public.usuarios u on u.id = ae.usuario_id
   where ae.aviso_id = p_aviso_id
     and ae.canal = 'email'
     and coalesce(u.notifs_reservas, true) = true
     and coalesce(trim(u.email), '') <> '';
$$;

grant execute on function public.aviso_destinatarios_email(bigint)
  to authenticated, service_role;


-- ══════════════════════════════════════════════════════════════════════════
-- LIMPIEZA
-- ══════════════════════════════════════════════════════════════════════════
-- 1. admin_upsert_estudio quedo duplicada: la version vieja de 20 parametros
--    (sin p_categorias) y la nueva de 21. PostgREST resuelve por nombre de
--    parametro asi que las dos "funcionan", pero la vieja no guarda
--    categorias y es una bomba de tiempo. Se borra por firma exacta.
drop function if exists public.admin_upsert_estudio(
  bigint, text, text, text, text, text, text, text, text, text,
  double precision, double precision, boolean, numeric, date, integer,
  text, text, integer, integer
);

-- 2. Restos de un pegado corrupto viejo: la funcion quedo creada sin el
--    prefijo 'admin_set_' del nombre original.
drop function if exists public.creditos_por_categoria(text);
